//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EF_LAB1_GestionLivres.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Adress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adress()
        {
            this.Membres = new HashSet<Membre>();
        }
    
        [Key]
        public int id_adress { get; set; }

        [DisplayName("Nº")]
        [StringLength(5)]
        public int numéro_civique { get; set; }

        [DisplayName("Rue")]
        [StringLength(10)]
        public string rue { get; set; }

        [DisplayName("Ville")]
        [StringLength(10)]
        public string ville { get; set; }

        [DisplayName("Code Postal")]
        [StringLength(10)]
        public string code_postal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membre> Membres { get; set; }
    }
}
