//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EF_LAB1_GestionLivres.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Livre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livre()
        {
            this.Emprunts = new HashSet<Emprunt>();
        }
        [Key]
        [DisplayName("Code du livre")]
        public int id_livre { get; set; }

        [StringLength(30)]
        [Required]
        public string ISBN { get; set; }

        [Required]
        [StringLength(30)]
        [DisplayName("Titre du Livre")]
        public string nom { get; set; }

        [DisplayName("Auteur")]
        [StringLength(30)]
        public string auteur { get; set; }


        [DisplayName("Année")]
        [Range(0000, 2017,ErrorMessage = "Année entre 0000 et 2017")]
        [StringLength(4)]
        public Nullable<int> annee { get; set; }

        [DisplayName("Editeur")]
        [StringLength(30)]
        public string editeur { get; set; }

        [DisplayName("Catégorie")]
        [StringLength(30)]
        public string categorie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprunt> Emprunts { get; set; }
    }
}
