//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EF_LAB1_GestionLivres.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Membre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membre()
        {
            this.Emprunts = new HashSet<Emprunt>();
        }

        [Key]
        [DisplayName("Code du Membre")]
        public int id_membre { get; set; }

        public int id_adress { get; set; }

        [Required]
        [StringLength(30)]
        [DisplayName("Nom")]
        public string nom { get; set; }

        [Required]
        [StringLength(30)]
        [DisplayName("Prénom")]
        public string prenom { get; set; }

        [Required]
        [StringLength(10)]
        [DisplayName("Tèlephone")]
        public string tel { get; set; }

        [Required]
        [DisplayName("Courriel")]
        [StringLength(30)]
        public string courriel { get; set; }

        [MaxLength(1)]
        //[Required(ErrorMessage = "F ou M")]
        [DisplayName("Sexe")]
        public string sex { get; set; }

        [DisplayName("Date de naissance")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        [Required]
        public Nullable<System.DateTime> dt_naissance { get; set; }
    
        public virtual Adress Adress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprunt> Emprunts { get; set; }
        public object Emprunt { get; internal set; }
    }
}
